[build]
  command = "npm run build"
  publish = "build"
  
[dev]
  command = "npm run dev"
  port = 5173

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=3600"

