[build]
  command = "npm run build"
  publish = "build"
  
[dev]
  command = "npm run dev"
  port = 5173

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "https://two34-designers-backend.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

